
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'nba_dbt_project'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'nba_dbt_project'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  nba_dbt_project:
    # Base models (raw data with light transformations)
    base:
      +materialized: view
      +schema: base
    
    # Intermediate models (business logic layer)
    intermediate:
      +materialized: table
      +schema: int
    
    # Marts (final presentation layer)
    marts:
      +materialized: table
      +schema: marts
# files using the `{{ config(...) }}` macro.
models:
  nba_dbt_project:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view
